[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "QtScriptEditorAdvanced"
version = "0.1.0"
authors = [
    { name = "András Zalavári", email = "zalavariandris@gmail.com" }
]
description = "Qt Python source editor with syntax highlighting."
requires-python = ">=3.10"
dependencies = [
    "qtpy",
    "pygments",
    "rope",
    "jedi"
]

[tool.hatch.build.targets.wheel]
packages = ["src/QtScriptEditorAdvanced"]
