[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vfxops"
version = "0.5.0"
authors = [
    { name = "András Zalavári", email = "zalavariandris@gmail.com" }
]
description = "A collection of functions for VFX operations"
requires-python = ">=3.10"
dependencies = [
    "pyglm",
    "opencv-python",
    "numba"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["vfxops", "vfxops.*"]
namespaces = false

[tool.setuptools.exclude-package-data]
"*" = ["__pycache__/*", ".venv_/*"]